### ISSUE TITLE
No platforms found 

### ISSUE THREAD

**Issue by pietro-sillano** [afarnudi/VirtualCellModel#8]
Hi @afarnudi 

I managed to install OpenMM on the cluster (I made all of the procedures logged to a GPU node), ran the test, benchmark it and everything seems fine:
``` shell
(openmm8) [psillano@gpu009 examples]$ python
Python 3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openmm
>>> openmm.openmm.Platform.getPlatformByName('CUDA')
<openmm.openmm.Platform; proxy of <Swig Object of type 'OpenMM::Platform *' at 0x1555544e8930> >
>>> openmm.openmm.Platform.getPlatformByName('CPU')
<openmm.openmm.Platform; proxy of <Swig Object of type 'OpenMM::Platform *' at 0x1555544e9290
```

Then I switch to VCM:
1. I change the OpenMM dir inside the makefile `OpenMM_INSTALL_DIR=/home/piano/openmm`
2. build it with make with no errors
3. export OpenMM's Dynamic Library and checked with `ldd ./VCM`  if every dynamic library is found
4. test `./VCM -c SimpleMembrane`  following your videos, that is the output:

```shell
(openmm8) [psillano@gpu009 bin]$ ./VCM -c SimpleMembrane  
  
Initialising the Membrane Class...  
Number of ... :  
Nodes   1002  
Triangles       2000  
Triangle pairs  3000  
Node pairs (Bonds) 3000  
  
Other properties:  
  
Radius  1  
Node pair (bond) distances:  
       Max 0.131936    Min 0.0943584   Average 0.120155  
Using the average mesh bond distances (0.120155) as the springs nominal length.  
Using 3.14159 (in radians) as the triangle pair nominal angle.  
Node radii set to half of bond average distances.  
  
Membrane class initiated.  
*************************  
  
  
Beginning the OpenMM section:  
Membrane 0  
Bond potential: Harmonic    
       Coeficient (KJ.Nm^-2.mol^-1 ) = 1  
Dihedral potential: Cosine(dihedral)  
       Coeficient (KJ . mol^-1 ) = 0.2  
Area and volume potentials:  
       Area potential: None  
       Volume potential: None  
Mean curvature potentials: None  
  
Simulation stats:  
1002 Atoms  
3000 Bonds  
3000 Dihedrals  
0 Angles  
  
Defining interactions...  
Periodic Boundry Condition Off  
  
OpenMM available platforms:  
Index Name        Speed (Estimated)  
(0)  Reference    1  
Please choose a pltform (index):    
0  
Segmentation fault (core dumped)
```

**Comment by afarnudi** [comment]
@pietro-sillano 
Everything seems to run pretty smoothly. I think I know what goes wrong with the platform identification (usually you should get at least three available platforms). VCM uses OpeMM's plugin path to identify the platforms OpenMM can use. Since OpenMM was installed in a different path, it can't locate the plugins. I will add an input flag option so that you can specify the location of the plugins during execution. I will let you know when it is fixed.

**Comment by afarnudi** [comment]
@pietro-sillano 
It is fixed. You can use the --ommPluginPath to input the path to the OpenMM's plugin path. 
If you run 
```./VCM -a```
You will get only the reference platform (uses only one core of the default CPU)
But if you specify the path to openmm's plugin, you will get the full list of available platforms (Should include OpenCL or CUDA if available on the cluster):
```./VCM -a --ommPluginPath /path/to/openmm/lib/plugins/```

**Comment by afarnudi** [comment]
@pietro-sillano 
Just to be clear, in order to see platforms on your machine you have to run:
```./VCM -c configuration.file --ommPluginPath path/to/openmm/lib/plugins```

**Comment by pietro-sillano** [comment]
Now I get also the CPU option but not CUDA
![image](https://github.com/afarnudi/VirtualCellModel/assets/45644034/097d6313-1170-4e66-8d40-98169bb21449)

**Comment by afarnudi** [comment]
@pietro-sillano 
This means everything is working correctly on VCM's side. The list of available platforms depends on how you built OpenMM. cmake can usually detect CUDA and OpenCL paths automatically if they are available. So if your machine has OpenCL installed (generally should have it) you need to make sure cmake is configured with the correct paths before installing OpenMM. With OpenCL you can parallalise computations on CPU and GPU (not just Nvidia GPUS). Plus, use platforms with single precision for faster calculations. U do not think you would need double precision for any sort of calculation.

**Comment by pietro-sillano** [comment]
@afarnudi 
Okay I understand. I have compiled openMM without OpenCL but for the moment I am satisfied with CUDA working ahah.

If I use OpenCL the parallelization on CPU would be automatic? without invoking mpi or openMP? and would there be a lot of difference with only CUDA?
